escalation:
  triggers:
    - "intent in {root_cause, forecasting, scenario_analysis} and doc_count >= 3"
    - "pre_confidence < 0.55"
    - "numeric_validation_failed"
    - "portfolio_size > 50"
confidence:
  formula: "0.35*R + 0.25*A + 0.25*V + 0.15*C"
  buckets: { high: ">=0.75", medium: "0.55-0.74", low: "<0.55" }
numeric_validation:
  checks:
    - "Aging buckets reconcile to OH"
    - "Units consistency (LT days vs demand cadence)"
    - "Currency presence and consistent"
    - "No negative OH unless flagged"
output_template:
  order: ["Title","Executive Insight","Analysis","Recommendations","Citations","Limits / Data Needed"]
