[theme]
# Let users choose their preferred theme in Settings (☰ menu → Settings → Theme)
primaryColor = "#4CAF50"
base = "light"

# Font
font = "sans serif"

[server]
# Development settings
runOnSave = true
allowRunOnSave = true

[browser]
# Automatically open browser
gatherUsageStats = false