[theme]
# Primary theme colors
primaryColor = "#4CAF50"           # Green accent color

# Base theme - dark mode by default (user can toggle in settings)
base = "dark"

# Font
font = "sans serif"

[server]
# Development settings
runOnSave = true
allowRunOnSave = true

[browser]
# Automatically open browser
gatherUsageStats = false