[theme]
# Force dark mode - users can still toggle in app settings (☰ menu → Settings → Theme)
base = "dark"
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

# Font
font = "sans serif"

[server]
# Development settings
runOnSave = true
allowRunOnSave = true

[browser]
# Automatically open browser
gatherUsageStats = false