OPENAI_API_KEY = "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")  # Replace with your real key
[sharepoint]
tenant_id = "5f7d12fe-a63c-4401-bde0-59342f7bb609"
client_id = "000183be-2bfd-4fdf-b9ff-2841e7bfd6c3"
client_secret = "66ab7a61-ecdd-4968-a82e-c834a28a3490"
site_url = "https://1sciesolutions.sharepoint.com/sites/EthosEnergy"
document_library = "Shared Documents/01_Project_Plan"
metadata_folder = "Shared Documents/01_Project_Plan/_metadata"
alias_file_path = "Shared Documents/01_Project_Plan/global_column_aliases.json"
raw_data_folder = "Shared Documents/Raw_Data/Raw_Data_Dumps"
