OPENAI_API_KEY = "sk-your-openai-key-here"  # Replace with your real key
[gdrive_service_account]
type = "service_account"
project_id = "ethosllm"
private_key_id = "76ac9bd12d5958d8fa3aef789178a685ccf582ae"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCbn6oATXQwUdMW
EPr6YTz6ng54UCagUJYfTctPy/SrHP2eX7W2tIQUb0dX1GLaUj7rPFVucUkEBaEt
/3uaRHTaCdmeGIR4DR3hvjCW7+sXTvrJW3I3eCuKH7F5YltFrgTu1Tc5xx3rH+lk
mwZo/Miw4wERnurRpBIsNBAOOK9qyM7noFUWd13OzxpIjUWcph18uGf7nXTEPAhz
suJtgL9fPz9+t3xr0q1d15RCTu4ms0azsM0lk8v2qg01VlqP+rgzrQHCpvGttpqz
0agcmyWZEawdLxwYbg7UJEJPGZMIvBiw8q9H7mH99v/wlP7ogrDAOP5NwHWF1Aqc
BGuurEEzAgMBAAECggEACorA0d9tUP6h/Xst/TsMDfAaC9VmIHMFEF7NOH0Y+GRw
28MhBJzq25WEMDNvdNmgcH/4S5B6AT8+YWbOoS8k+UY0iyyfAKDm1s1y7i6Xbs9H
Vs+Oh6pozKUD+TSL+UbmB6XC5XOTF8PkJBAKWZ9SGwVto5tvzb6/CmaGdegqHeIc
cybL52/nho/AibzuJquf/Bs94bzRlIcHO67C/OQVm7JhWMr6iR/6dlORT1VoODmJ
wSVokzy8QAi6VOzt+yPstg8xO390xO7uJERFuGov0yDJSLsR2NQRB5fqgn1/jLp2
6r1OGYX1Oa8RQIaZWl82HgEkZx4i2gU3WHrRO5WneQKBgQDIPjITkgRJbK59an3l
jKWeilQwSXD6+Vu6Cx/um/inVo23eGU3UIUTJLS8xddEV9WDWr7E020Q4D+BG1G/
RSgy3p9H1NLmpuR6TPK70o9wgqLD1MBcsOIe0pq0f6dH0XcxVNLi4Zoy5waSGLri
4o6kFL2aNh63yVdktFN38VJ+ewKBgQDG9OYbj5b6StCn2l8S0Mk+o1Ij+d4Xg0en
fMkeOL8MQRb1x0aS8oFDtZo6PeOqSmWXmTtINFIudT8EwUlgYmIzGqU41juXrQa2
QnX5mU96T0ifmKbhFhJ55o26iMdROo4g+8EuS2V4Bs4fYr6jtWvvE2C6Bpb9EkIn
z6LIhqmmqQKBgFPwPm2Vt9ZPiJVqHnwrCQH8Wm4jWwjZnmnOYARVvVXoIl/WSBd3
2VC9AkZfaG1tpEL7txwqxH1eg0BLg2j6RG+OgpZJ0F5/dycNOnMhQJ+ZI0GT3U79
lsv03ITtPeINHDnBpOUWTN0pmseDNlQFRGXji9co+Jdx/wBn1tVgg4QhAoGAEgOu
qiQwOW14wxoErcF111QWZeeD8oEShdnIpBHjSorCN3LZswh+J9FTq55a9NpTpIxd
T8ZdApPfJuERcca2uYXaG/FZ5/vktbAC2pzFE4AGRV0fDxZeiecUQiWMVpCEufvR
nA17nIiRNUpNlKkior0QbweVuEhk8RHd3WZECjECgYA55X7LibqYyZl3GVaRMVBk
Mbd5pMkprOxnp9ob/2DAr5VKUVeroHP3VPlB8Fg66AMnP1PRkU0HHGqlR42R3bDq
BHo7JgqyDXZ9cI+TbwxihEA1x8SF4zwc4EG4oR4aADQO0o3wIguJB8nV4zkzJu9w
e+hdIQsF3dwaKNUDhm2H+Q==
-----END PRIVATE KEY-----"""
client_email = "ethosllm@ethosllm.iam.gserviceaccount.com"
client_id = "100893624035809214602"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ethosllm@ethosllm.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
